# Generated by Django 4.2.15 on 2024-08-21 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text='Heading of the About Us section', max_length=255)),
                ('content', models.TextField(help_text='Main content of the About Us section')),
                ('image', models.ImageField(help_text='Image for the About Us section', upload_to='about/')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the carousel item', max_length=255)),
                ('content', models.TextField(help_text='Content of the carousel item')),
                ('image', models.ImageField(help_text='Image for the carousel item', upload_to='carousel/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Icon class for FontAwesome', max_length=255)),
                ('description', models.CharField(help_text='Short description for the feature', max_length=255)),
                ('title', models.CharField(help_text='Title for the feature', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RoomOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(help_text='Type of the room', max_length=255)),
                ('room_number', models.CharField(help_text='Room number associated with the offer', max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Cost per night', max_digits=10)),
                ('short_description', models.TextField(help_text='Short description of the offer')),
                ('image', models.ImageField(help_text='Image for the offer', upload_to='room/')),
            ],
        ),
        migrations.CreateModel(
            name='RoomFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(help_text='Name of the facility', max_length=255)),
                ('room_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='turag.roomoffer')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person making the booking', max_length=255)),
                ('email', models.EmailField(help_text='Email address of the person making the booking', max_length=254)),
                ('phone', models.CharField(help_text='Phone number of the person making the booking', max_length=20)),
                ('adult', models.PositiveIntegerField(help_text='Number of adults')),
                ('children', models.PositiveIntegerField(help_text='Number of children')),
                ('checkin', models.DateField(help_text='Check-in date')),
                ('checkout', models.DateField(help_text='Check-out date')),
                ('have_to_pay', models.DecimalField(blank=True, decimal_places=2, help_text='Amount that needs to be paid', max_digits=10, null=True)),
                ('room', models.ForeignKey(help_text='Room associated with the booking', on_delete=django.db.models.deletion.CASCADE, to='turag.roomoffer')),
            ],
        ),
    ]
