# Generated by Django 4.2.15 on 2024-08-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResortInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(help_text='Upload the resort logo.', upload_to='logos/')),
                ('description', models.TextField(help_text='A brief description of the resort.')),
                ('facebook_link', models.URLField(blank=True, help_text='Link to the resort’s Facebook page.')),
                ('instagram_link', models.URLField(blank=True, help_text='Link to the resort’s Instagram profile.')),
                ('youtube_link', models.URLField(blank=True, help_text='Link to the resort’s YouTube channel.')),
                ('whatsapp_link', models.URLField(blank=True, help_text='Link to the resort’s WhatsApp contact.')),
                ('twitter_link', models.URLField(blank=True, help_text='Link to the resort’s Twitter profile.')),
                ('pinterest_link', models.URLField(blank=True, help_text='Link to the resort’s Pinterest page.')),
                ('tiktok_link', models.URLField(blank=True, help_text='Link to the resort’s TikTok profile.')),
                ('address', models.CharField(help_text='Resort address.', max_length=255)),
                ('phone_number', models.CharField(blank=True, help_text='Resort phone number.', max_length=20)),
                ('email', models.EmailField(help_text='Resort email address.', max_length=254)),
            ],
            options={
                'verbose_name': 'Resort Information',
                'verbose_name_plural': 'Resort Information',
            },
        ),
    ]
