# Generated by Django 4.2.15 on 2024-08-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turag', '0002_resortinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Turag Waterfront Resort', max_length=255)),
                ('heading', models.CharField(default='Make Memories', max_length=255)),
                ('subheading', models.CharField(default='Discover the place where you have fun & enjoy a lot', max_length=255)),
            ],
        ),
    ]
