# Generated by Django 4.2.15 on 2024-12-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turag', '0004_alter_resortinfo_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('keywords', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
