# Generated by Django 4.2.15 on 2024-12-29 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('turag', '0005_servicemeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('keywords', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='servicemeta',
            name='keywords',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
