# Generated by Django 4.2.15 on 2024-12-29 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('turag', '0006_homemeta_alter_servicemeta_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('keywords', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='homemeta',
            name='keywords',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
