# Generated by Django 4.2.15 on 2025-02-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turag', '0007_blogmeta_alter_homemeta_keywords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmeta',
            options={'verbose_name': 'Blog SEO', 'verbose_name_plural': 'Blog SEO'},
        ),
        migrations.AlterModelOptions(
            name='homemeta',
            options={'verbose_name': 'Home SEO', 'verbose_name_plural': 'Home SEO'},
        ),
        migrations.AlterModelOptions(
            name='servicemeta',
            options={'verbose_name': 'Service SEO', 'verbose_name_plural': 'Service SEO'},
        ),
        migrations.AlterField(
            model_name='blogmeta',
            name='keywords',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
